---
- name: 创建临时目录存放镜像
  file:
    path: "/tmp/images"
    state: directory
    mode: '0755'

- name: 查找所有镜像（tar）文件
  ansible.builtin.find:
    path: "{{ playbook_dir }}/images/"
    patterns: '*.tar'
    recurse: no
  delegate_to: localhost
  register: tar_files
  run_once: true  # 仅在控制节点执行一次


- name: 复制镜像文件到目标节点
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/images/{{ item | basename }}"
    dest: "/tmp/images/{{ item | basename }}"
    mode: '0644'
  with_items: "{{ tar_files.files | map(attribute='path') | list }}"
  when: tar_files.files | length > 0  # 确保只在有文件时执行


- name: 加载镜像文件到 Docker
  shell: "docker load -i /tmp/images/{{ item | basename }}"
  with_items: "{{ tar_files.files | map(attribute='path') | list }}"
  when: tar_files.files | length > 0  # 确保只在有文件时执行


