---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: virt-tool-centos
  namespace: kube-system
  labels:
    app: virt-tool-centos
spec:
  selector:
    matchLabels:
      app: virt-tool-centos
  template:
    metadata:
      labels:
        app: virt-tool-centos
    spec:
      nodeSelector:
        doslab/virt.tool.centos: ""
      hostNetwork: true
      containers:
      - image: g-ubjg5602-docker.pkg.coding.net/iscas-system/containers/univirt-centos7-virtctl:v1.0.0
        command: 
        - bash
        - 'virtctl-update-stuff.sh'
        imagePullPolicy: Always
        name: virtctl
        securityContext:
          runAsUser: 0
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add: 
            - SYS_TIME
        volumeMounts:
          - name: varlog
            mountPath: /var/log/
          - name: kube
            mountPath: /root/.kube/
          - name: libvirt
            mountPath: /var/lib/libvirt/
          - name: etc
            mountPath: /etc/
          - name: cgroup
            mountPath: /sys/fs/cgroup/
          - name: varrun
            mountPath: /var/run/
          - name: usrbin
            mountPath: /usr/bin
          - name: kubebin
            mountPath: /opt/kube/bin
          - name: bashrc
            mountPath: /root/.bashrc
          - name: usrlib
            mountPath: /usr/lib
          - name: localbin
            mountPath: /usr/local/bin
          - name: ssh
            mountPath: /root/.ssh
      - image: g-ubjg5602-docker.pkg.coding.net/iscas-system/containers/univirt-centos7-virtlet:v1.0.0
        command: 
        - bash
        - 'virtlet-update-stuff.sh'
        imagePullPolicy: Always
        name: virtlet
        securityContext:
          runAsUser: 0
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add: 
            - SYS_TIME
        volumeMounts:
          - name: varlog
            mountPath: /var/log/
          - name: kube
            mountPath: /root/.kube/
          - name: libvirt
            mountPath: /var/lib/libvirt/
          - name: etc
            mountPath: /etc/
          - name: cgroup
            mountPath: /sys/fs/cgroup/
          - name: varrun
            mountPath: /var/run/
          - name: usrbin
            mountPath: /usr/bin
          - name: kubebin
            mountPath: /opt/kube/bin
          - name: bashrc
            mountPath: /root/.bashrc
          - name: usrlib
            mountPath: /usr/lib
          - name: localbin
            mountPath: /usr/local/bin
          - name: ssh
            mountPath: /root/.ssh
      - image: g-ubjg5602-docker.pkg.coding.net/iscas-system/containers/univirt-centos7-libvirtwatcher:v1.0.0
        command: 
        - bash
        - 'watcher.sh'
        imagePullPolicy: Always
        name: libvirtwatcher
        securityContext:
          runAsUser: 0
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add: 
            - SYS_TIME
        volumeMounts:
          - name: varlog
            mountPath: /var/log/
          - name: kube
            mountPath: /root/.kube/
          - name: libvirt
            mountPath: /var/lib/libvirt/
          - name: etc
            mountPath: /etc/
          - name: cgroup
            mountPath: /sys/fs/cgroup/
          - name: varrun
            mountPath: /var/run/
          - name: usrbin
            mountPath: /usr/bin
          - name: kubebin
            mountPath: /opt/kube/bin
          - name: bashrc
            mountPath: /root/.bashrc
          - name: usrlib
            mountPath: /usr/lib
          - name: localbin
            mountPath: /usr/local/bin
          - name: ssh
            mountPath: /root/.ssh
      - image: g-ubjg5602-docker.pkg.coding.net/iscas-system/containers/univirt-centos7-virtmonitor:v1.0.0
        command: 
        - bash
        - 'monitor.sh'
        imagePullPolicy: Always
        name: virtmonitor
        securityContext:
          runAsUser: 0
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add: 
            - SYS_TIME
        volumeMounts:
          - name: varlog
            mountPath: /var/log/
          - name: kube
            mountPath: /root/.kube/
          - name: libvirt
            mountPath: /var/lib/libvirt/
          - name: etc
            mountPath: /etc/
          - name: cgroup
            mountPath: /sys/fs/cgroup/
          - name: varrun
            mountPath: /var/run/
          - name: usrbin
            mountPath: /usr/bin
          - name: kubebin
            mountPath: /opt/kube/bin
          - name: bashrc
            mountPath: /root/.bashrc
          - name: usrlib
            mountPath: /usr/lib
          - name: localbin
            mountPath: /usr/local/bin
          - name: ssh
            mountPath: /root/.ssh
      volumes: 
        - name: varlog
          hostPath: 
            path: /var/log/
        - name: kube
          hostPath: 
            path: /root/.kube/
        - name: libvirt
          hostPath: 
            path: /var/lib/libvirt/
        - name: varrun
          hostPath: 
            path: /var/run/
        - name: etc
          hostPath: 
            path: /etc/
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup/
        - name: usrbin
          hostPath:
            path: /usr/bin/
        - name: kubebin
          hostPath:
            path: /opt/kube/bin
        - name: bashrc
          hostPath:
            path: /root/.bashrc
        - name: usrlib
          hostPath:
            path: /usr/lib
        - name: localbin
          hostPath:
            path: /usr/local/bin
        - name: ssh
          hostPath:
            path: /root/.ssh