---
- name: 创建 Prometheus 命名空间
  kubernetes.core.k8s:
    name: prometheus
    kind: Namespace
    api_version: v1
    state: present
  when: is_master == 1

- name: 清理 prometheus 命名空间下的所有 Deployment
  kubernetes.core.k8s:
    kind: Deployment
    namespace: prometheus
    state: absent
    all: true  # 删除该命名空间下所有 Deployment
  when: is_master == 1  # 仅在控制节点执行（与现有部署逻辑一致）


- name: 清理 prometheus 命名空间下的所有 Service
  kubernetes.core.k8s:
    kind: Service
    namespace: prometheus
    state: absent
    all: true  # 删除该命名空间下所有 Service
  when: is_master == 1  # 仅在控制节点执行（与现有部署逻辑一致）

- name: 清理 prometheus 命名空间下的所有 DaemonSet
  kubernetes.core.k8s:
    kind: DaemonSet
    namespace: prometheus
    state: absent
    all: true  # 删除该命名空间下所有 DaemonSet
  when: is_master == 1  # 仅在控制节点执行（与现有部署逻辑一致）

- name: 清理 prometheus 命名空间下的所有 Pod
  kubernetes.core.k8s:
    kind: Pod
    namespace: prometheus
    state: absent
    all: true  # 删除该命名空间下所有 Pods
  when: is_master == 1  # 仅在控制节点执行（与现有部署逻辑一致）

- name: 复制 Prometheus serviceAccount 部署文件
  copy:
    src: "files/prometheus-serviceaccount.yaml"
    dest: "/tmp/prometheus-serviceaccount.yaml"
  when: is_master == 1

- name: 部署 Prometheus serviceAccount
  kubernetes.core.k8s:
    src: "/tmp/prometheus-serviceaccount.yaml"
    state: present
  when: is_master == 1

- name: 复制 Prometheus rbac 部署文件
  copy:
    src: "files/prometheus-rbac.yaml"
    dest: "/tmp/prometheus-rbac.yaml"
  when: is_master == 1

- name: 部署 Prometheus rbac
  kubernetes.core.k8s:
    src: "/tmp/prometheus-rbac.yaml"
    state: present
  when: is_master == 1


- name: 复制 Prometheus 部署文件
  copy:
    src: "files/prometheus-deploy.yaml"
    dest: "/tmp/prometheus-deploy.yaml"
  when: is_master == 1

- name: 部署 Prometheus
  kubernetes.core.k8s:
    src: "/tmp/prometheus-deploy.yaml"
    state: present
  when: is_master == 1

