---
- name: 创建 Grafana 数据源
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: grafana-datasources
        namespace: prometheus
      data:
        prometheus.yml: |
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus:9090
            access: proxy
            isDefault: true

- name: 部署Grafana
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
        namespace: prometheus
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: grafana
        template:
          metadata:
            labels:
              app: grafana
          spec:
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Exists"
                effect: "NoSchedule"
              - key: "node-role.kubernetes.io/master"
                operator: "Exists"
                effect: "NoSchedule"
            containers:
              - name: grafana
                image: grafana/grafana:9.5.2
                imagePullPolicy: Never
                ports:
                  - containerPort: 3000
                volumeMounts:
                  - name: grafana-datasources
                    mountPath: /etc/grafana/provisioning/datasources
                env:
                  - name: GF_SECURITY_ADMIN_USER
                    value: "admin"  # 固定用户名
                  - name: GF_SECURITY_ADMIN_PASSWORD
                    value: "admin"  # 固定密码
                  - name: GF_USERS_ALLOW_SIGN_UP
                    value: "false"
                  - name: GF_LANG
                    value: "zh-CN"  # 中文界面
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
            volumes:
              - name: grafana-datasources
                configMap:
                  name: grafana-datasources


- name: 创建 Grafana NodePort (30093) 服务
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: grafana
        namespace: prometheus
      spec:
        selector:
          app: grafana
        ports:
          - port: 3000
            targetPort: 3000
            nodePort: 30093
        type: NodePort