---
- name: Ensure Docker CLI plugin directory exists
  ansible.builtin.file:
    path: "/usr/libexec/docker/cli-plugins"
    state: directory
    mode: '0755'

- name: 复制镜像文件到目标节点
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/buildx-v0.11.2.linux-amd64"
    dest: "/usr/libexec/docker/cli-plugins/docker-buildx"
    mode: '0755'

- name: Set Buildx as default builder
  ansible.builtin.command: docker buildx install
  register: install_result
  changed_when: "'is now installed' in install_result.stdout"
